server:
  port: 8087

spring:
  application:
    name: SEARCH-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registy: true
    service-url:
      default-zone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%green([%d{dd-MM-yyyy HH:mm:ss}]) %magenta([%thread]) %highlight([%-5level]) [%logger -> %M.%line] => %highlight(%msg%n)"
  level:
    com.userservice: DEBUG
    root: INFO



